feat: add health check

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -13,6 +13,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up JDK 21
         uses: actions/setup-java@v3
         with:
@@ -22,8 +23,10 @@ jobs:
 
       - name: Test with Maven
         run: mvn clean install -Ptest
+
       - name: Update dependency graph
         uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+
       - name: Execute update.sh on VPS
         uses: appleboy/ssh-action@master
         with:
@@ -31,5 +34,15 @@ jobs:
           username: ${{ secrets.VPS_USERNAME }}
           password: ${{ secrets.VPS_PASSWORD }}
           script: |
-            cd /srv/vocabulary-learning-tool  &&
+            cd /srv/vocabulary-learning-tool &&
             sudo ./update.sh
+
+      - name: Health Check
+        run: |
+          sleep 10 # wait for the server to start
+          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://your-app-url/health)
+          if [ "$response" -ne 200 ]; then
+            echo "Health check failed with status code $response"
+            exit 1
+          fi
+          echo "Health check succeeded with status code $response"
